### ISSUE TITLE
Report the day & date of previous entries

### ISSUE THREAD

**Issue by danvk** [parterburn/dabble.me#33]
I imported OhLife entries last year, so I occasionally get very old journal entries attached to my dabble.me prompts. For example:

> Oh snap, remember this? Exactly 1,210 days ago you wrote...

It's hard for me to subtract 1,210 days in my head. This would be more helpful if written as:

> Oh snap, remember this? Exactly 1,210 days ago (Sat., Sept. 29, 2012) you wrote...

Or it could be added as a footer:

> Oh snap, remember this? Exactly 1,210 days ago you wrote...
> ...entry...
> Saturday, September 29, 2012

If this seems like a reasonable change, I'd be happy to implement it.

**Comment by danvk** [comment]
Thanks! Lightning-fast turnaround :)

**Comment by parterburn** [comment]
@danvk still needs some tweaking for mobile-friendly...I'll do some thinking.
