### ISSUE TITLE
Report the weather from previous entries

### ISSUE THREAD

**Issue by danvk** [parterburn/dabble.me#34]
Timehop shows a line like:

"1 year ago; 42° F and sunny" 

This would be nice to see attached to previous dabble.me entries, too. It gives a bit of context for the entry without any effort on the writer's part.

This would require that the user specify a home city somewhere in the preferences.

**Comment by parterburn** [comment]
@danvk I'm personally not a big fan of this (don't really see the added value), but I'll be sure and listen for any requests like this to revisit as needed.

If you're using Dabble Me for other reasons (travel journal, baby journal, etc) the weather doesn't make a lot of sense (in fact, it would be inaccurate for a travel journal). There are tags available that wouldn't be much more effort on the users part, if context is necessary. For example, you could tag something "#sunny" or "#raining" to group posts together by like weather.

**Comment by danvk** [comment]
Agreed that this is an easier sell for a tool like Timehop which has access to your location through other means (checkins, photo metadata, etc.). Feel free to close this out if you're unlikely to implement it.
