### ISSUE TITLE
Entries page breaks words wherever it feels like in Gecko

### ISSUE THREAD

**Issue by sparkyb** [parterburn/dabble.me#38]
Due to the use of word-break: break-all, if you read entries in Firefox (or SeaMonkey as I do) it just breaks words between any letters which is a bit distracting. It works fine on WebKit (Chrome) because of the word-break: break-words right after, but that value is non-standard and unsupported in Firefox.

**Comment by parterburn** [comment]
Fixed with 4bb19ebdad0d9da77d49fe9e3a25d18c74907acd
