### ISSUE TITLE
Preserve paragraphs in emails

### ISSUE THREAD

**Issue by brynious** [parterburn/dabble.me#94]
If a users email post has multiple paragraphs, the newlines are stripped out and the result is a single block of text.

**Comment by parterburn** [comment]
@brynious  this is intended behavior for free users. Are you experiencing it as a PRO user?

**Comment by brynious** [comment]
Yeah I'm on the PRO plan. First screenshot is the email and second screenshot is how it's rendered in the web app.

I guess it's catching that they're on new lines, but should it be preserving the multi-newlines which separate paragraphs?

<img width="261" alt="image" src="https://github.com/parterburn/dabble.me/assets/24630513/734a57ec-874e-4b39-9ab0-4f68aa415410">

<img width="354" alt="image" src="https://github.com/parterburn/dabble.me/assets/24630513/9e47ad39-b286-4419-8a14-5f2bc8fe1fd1">
